---
- name: Instalar Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Asegurar que Apache este iniciado y habilitado
  service:
    name: apache2
    state: started
    enabled: true

- name: Copiar pagina personalizada
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Reiniciar apache
